---
version: 3.7

services:
  argot:
    container_name: argot
    build: .
    volumes:
      - ./:/app:Z
    # override entrypoint so the container starts
    # and can 'see' the redis container
    # connect to it via docker exec -it -w /app argot /bin/bash
    entrypoint: 
      - tail
      - -f
      - /dev/null

  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data:Z

