name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6.7, 2.7.6, 3.0.4, 3.1.2, jruby-9.3.8.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v2
        with:
          path: $HOME/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libxml2-dev libxslt-dev cmake
          gem update --system
          bundle update
      - name: Run tests
        run: rspec
